"""Add polls and poll_votes tables

Revision ID: b26ddd87f5d0
Revises: 70241399664e
Create Date: 2025-12-17 04:38:48.015234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26ddd87f5d0'
down_revision = '70241399664e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
